/* eslint-disable react-hooks/purity -- server-rendered expiry calculations intentionally use request time */
import Link from "next/link";
import { db } from "@/lib/db";
import { Empty, PageHeader, Status } from "../_components/ui";
import { SyncButton } from "../_components/sync-button";
import { RegisterDevice, RevokeCertificate } from "./actions-client";
import { CreateProfile, ProfileActions } from "./profile-actions";
const tabs = [["certificates", "Certificates"], ["devices", "Devices"], ["profiles", "Profiles"], ["bundle-ids", "Bundle IDs"]] as const;
export default async function Developer({ searchParams }: { searchParams: Promise<{ tab?: string }> }) {
  const { tab = "certificates" } = await searchParams;
  const [certificates, devices, profiles, bundles] = await Promise.all([db.certificate.findMany({ orderBy: { expirationDate: "asc" } }), db.registeredDevice.findMany({ orderBy: { name: "asc" } }), db.provisioningProfile.findMany({ orderBy: { expirationDate: "asc" } }), db.bundleId.findMany({ orderBy: { name: "asc" } })]);
  return <><PageHeader eyebrow="Provisioning" title="Developer resources" description="Certificates, devices, profiles and bundle identifiers cached from Apple." action={<SyncButton domain="developer" label="Sync resources" />} />
    <nav className="mb-5 flex gap-1 overflow-x-auto border-b" aria-label="Developer resource views">{tabs.map(([value, label]) => <Link key={value} href={`/developer?tab=${value}`} className={`min-h-11 shrink-0 border-b-2 px-4 py-3 text-sm font-semibold ${tab === value ? "border-blue-700 text-blue-800" : "border-transparent text-slate-600"}`}>{label}</Link>)}</nav>
    {tab === "devices" && <><RegisterDevice />{devices.length ? <div className="card overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="px-5 py-3">Name</th><th className="px-5 py-3">UDID</th><th className="px-5 py-3">Platform</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y">{devices.map(device => <tr key={device.id}><td className="px-5 py-4 font-semibold">{device.name}</td><td className="px-5 py-4 font-mono text-xs">{device.udid}</td><td className="px-5 py-4">{device.platform}</td><td className="px-5 py-4"><Status value={device.status} /></td></tr>)}</tbody></table></div> : <Empty title="No registered devices" text="Sync Apple or register a device with its name and UDID." />}</>}
    {tab === "certificates" && (certificates.length ? <div className="grid gap-3">{certificates.map(certificate => { const days = certificate.expirationDate ? Math.ceil((certificate.expirationDate.getTime() - Date.now()) / 86400000) : null, status = !certificate.activated ? "Revoked" : days !== null && days < 0 ? "Expired" : days !== null && days < 7 ? "Expires < 7 days" : days !== null && days < 30 ? "Expires < 30 days" : "Active", name = certificate.displayName ?? certificate.name ?? certificate.id; return <section className="card p-5" key={certificate.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-semibold">{name}</h2><p className="muted mt-1 text-sm">{certificate.certificateType} · {certificate.platform ?? "All platforms"}</p><p className="muted mt-1 font-mono text-xs">{certificate.serialNumber ?? certificate.id}</p></div><div className="text-right"><Status value={status} /><p className="muted mt-2 text-xs">{certificate.expirationDate?.toLocaleString() ?? "No expiration date"}</p>{certificate.activated && <RevokeCertificate id={certificate.id} name={name} />}</div></div></section>; })}</div> : <Empty title="No certificates synced" text="Sync developer resources to monitor certificate expiration." />)}
    {tab === "profiles" && <><CreateProfile bundles={bundles.map(({ id, name, identifier }) => ({ id, name, identifier }))} />{profiles.length ? <div className="card overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="px-5 py-3">Name</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Platform</th><th className="px-5 py-3">Expires</th><th className="px-5 py-3">Status</th><th className="px-5 py-3"><span className="sr-only">Actions</span></th></tr></thead><tbody className="divide-y">{profiles.map(profile => <tr key={profile.id}><td className="px-5 py-4 font-semibold">{profile.name}</td><td className="px-5 py-4">{profile.profileType}</td><td className="px-5 py-4">{profile.platform}</td><td className="px-5 py-4">{profile.expirationDate?.toLocaleDateString() ?? "—"}</td><td className="px-5 py-4"><Status value={profile.profileState} /></td><td className="px-5 py-4 text-right"><div className="mb-2"><a className="font-semibold text-blue-700" href={`/api/developer/profiles/${profile.id}/download`}>Download</a></div><ProfileActions id={profile.id} name={profile.name} /></td></tr>)}</tbody></table></div> : <Empty title="No profiles synced" text="Create a profile with safe defaults or sync developer resources." />}</>}
    {tab === "bundle-ids" && (bundles.length ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{bundles.map(bundle => <div className="card p-5" key={bundle.id}><h2 className="font-semibold">{bundle.name}</h2><p className="muted mt-2 break-all font-mono text-xs">{bundle.identifier}</p><p className="mt-4 text-sm">{bundle.platform}</p></div>)}</div> : <Empty title="No bundle IDs synced" text="Sync developer resources to load identifiers registered with Apple." />)}
  </>;
}
