"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Command, LoaderCircle, Search, X } from "lucide-react";

type Result = { id: string; type: string; title: string; subtitle: string; href: string };
const commands = [{ title: "Add tester", subtitle: "Choose an app", href: "/apps" }, { title: "Find tester", subtitle: "All TestFlight testers", href: "/testflight/testers" }, { title: "Register device", subtitle: "Developer resources", href: "/developer?tab=devices" }, { title: "View failed operations", subtitle: "Operations center", href: "/operations?status=failed" }];

export function CommandPalette() {
  const [open, setOpen] = useState(false), [query, setQuery] = useState(""), [results, setResults] = useState<Result[]>([]), [busy, setBusy] = useState(false);
  const input = useRef<HTMLInputElement>(null), router = useRouter();
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setOpen(value => !value); } if (event.key === "Escape") setOpen(false); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, []);
  useEffect(() => { if (open) setTimeout(() => input.current?.focus(), 0); }, [open]);
  useEffect(() => { if (query.trim().length < 2) return; const controller = new AbortController(), timer = setTimeout(async () => { setBusy(true); try { const response = await fetch(`/api/search?q=${encodeURIComponent(query)}`, { signal: controller.signal }); const body = await response.json(); if (response.ok) setResults(body.results); } finally { setBusy(false); } }, 180); return () => { clearTimeout(timer); controller.abort(); }; }, [query]);
  async function sync() { setBusy(true); const response = await fetch("/api/sync", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ domain: "apps" }) }); setBusy(false); if (response.ok) { setOpen(false); router.push("/operations"); router.refresh(); } }
  return <><button className="btn btn-secondary !min-h-9 text-sm" onClick={() => setOpen(true)} aria-label="Open global search"><Search className="size-4" aria-hidden /><span className="hidden sm:inline">Search</span><kbd className="hidden rounded border px-1.5 py-0.5 font-mono text-[10px] text-slate-500 md:inline">⌘K</kbd></button>{open && <div className="fixed inset-0 z-50 bg-slate-950/40 p-4 pt-[10vh]" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) setOpen(false); }}><section className="mx-auto max-w-2xl overflow-hidden rounded-xl border bg-white shadow-2xl" role="dialog" aria-modal="true" aria-label="Search and commands"><div className="flex items-center gap-3 border-b px-4"><Search className="size-5 text-slate-400" aria-hidden /><input ref={input} className="h-14 min-w-0 flex-1 bg-transparent outline-none" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search apps, testers, builds, operations…" aria-label="Search" />{busy && <LoaderCircle className="size-4 animate-spin" aria-hidden />}<button className="p-2" onClick={() => setOpen(false)} aria-label="Close"><X className="size-5" /></button></div><div className="max-h-[60vh] overflow-y-auto p-2">{query.length < 2 ? <><p className="eyebrow px-3 py-2">Commands</p>{commands.map(item => <Link key={item.title} href={item.href} onClick={() => setOpen(false)} className="flex items-center gap-3 rounded-lg px-3 py-3 hover:bg-slate-100"><Command className="size-4 text-slate-500" aria-hidden /><span><strong className="block text-sm">{item.title}</strong><span className="muted text-xs">{item.subtitle}</span></span></Link>)}<button onClick={sync} className="flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left hover:bg-slate-100"><Command className="size-4 text-slate-500" aria-hidden /><span><strong className="block text-sm">Sync Apple</strong><span className="muted text-xs">Refresh apps and team data</span></span></button></> : results.length ? results.map(item => <Link key={item.id} href={item.href} onClick={() => setOpen(false)} className="block rounded-lg px-3 py-3 hover:bg-slate-100"><span className="eyebrow">{item.type}</span><strong className="mt-1 block text-sm">{item.title}</strong><span className="muted text-xs">{item.subtitle}</span></Link>) : !busy && <p className="muted p-8 text-center text-sm">No matching apps, testers, builds, or operations.</p>}</div></section></div>}</>;
}
